# Лабораторна робота 1
Стельмах Ліана

In [2]:
import numpy as np

In [3]:
#1.Створіть одновимірний масив (вектор) з першими 20-ма натуральними числами та виведіть його значення.
vector = np.arange(1, 21)
print("Одновимірний масив:", vector)

Одновимірний масив: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [4]:
#2. Створіть двовимірний масив (матрицю) розміром 4x4, заповніть його одиницями та виведіть його значення.
matrix_ones = np.ones((4, 4))
print("\nМатриця 4x4, заповнена одиницями:\n", matrix_ones)


Матриця 4x4, заповнена одиницями:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [5]:
#3.Створіть масив розміром 5x5, заповніть його випадковими дійсними числами в діапазоні від -1 до 1 та виведіть його значення.
matrix_random = np.random.uniform(-1, 1, (5, 5))
print("\nМатриця 5x5 з випадковими числами від -1 до 1:\n", matrix_random)


Матриця 5x5 з випадковими числами від -1 до 1:
 [[-0.81667923 -0.11303406  0.7216123   0.35313365 -0.99673034]
 [-0.78329107  0.69029738 -0.98300118  0.01814223  0.085685  ]
 [ 0.6613436  -0.76848245  0.25767055 -0.74508594 -0.29306977]
 [-0.46770867  0.62121297  0.27679007 -0.02021846 -0.35491075]
 [-0.30466738 -0.72039574 -0.10835809 -0.96542371  0.21724746]]


In [6]:
#4.Створіть масив розміром 3x3, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.
matrix_random_0_1 = np.random.rand(3, 3)
print("\nМатриця 3x3 з випадковими числами від 0 до 1:\n", matrix_random_0_1)


Матриця 3x3 з випадковими числами від 0 до 1:
 [[0.81942429 0.81548436 0.58528723]
 [0.53012041 0.1855413  0.33930676]
 [0.28175053 0.35001992 0.96360771]]


In [7]:
#5. Створіть два одновимірних масиви розміром 6, заповніть їх випадковими цілими числами в діапазоні від 1 до 20 та виконайте на них поелементні операції
array1 = np.random.randint(1, 21, 6)
array2 = np.random.randint(1, 21, 6)
print("\nМасив 1:", array1)
print("Масив 2:", array2)
print("Сума:", array1 + array2)
print("Різниця:", array1 - array2)
print("Добуток:", array1 * array2)


Масив 1: [17 14  7 10  1 11]
Масив 2: [15  5  4  6  9  3]
Сума: [32 19 11 16 10 14]
Різниця: [ 2  9  3  4 -8  8]
Добуток: [255  70  28  60   9  33]


In [8]:
#6. Створіть дві матриці розміром 3x2 та 2x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 5 та перемножте їх між собою.
matrix_a = np.random.randint(1, 6, (3, 2))
matrix_b = np.random.randint(1, 6, (2, 4))
matrix_product = np.dot(matrix_a, matrix_b)
print("\nМатриця 3x2:\n", matrix_a)
print("Матриця 2x4:\n", matrix_b)
print("Добуток матриць:\n", matrix_product)


Матриця 3x2:
 [[1 5]
 [5 2]
 [1 5]]
Матриця 2x4:
 [[5 3 2 1]
 [5 5 5 1]]
Добуток матриць:
 [[30 28 27  6]
 [35 25 20  7]
 [30 28 27  6]]


In [9]:
#7. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.
matrix_transpose = np.random.rand(3, 3)
print("\nОригінальна матриця:\n", matrix_transpose)
print("Транспонована матриця:\n", matrix_transpose.T)


Оригінальна матриця:
 [[0.24482881 0.08407729 0.21460203]
 [0.24862906 0.63464218 0.73111935]
 [0.28493578 0.13646599 0.87668497]]
Транспонована матриця:
 [[0.24482881 0.24862906 0.28493578]
 [0.08407729 0.63464218 0.13646599]
 [0.21460203 0.73111935 0.87668497]]


In [10]:
#8. Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.
matrix_diff_a = np.random.randint(1, 11, (3, 3))
matrix_diff_b = np.random.randint(1, 11, (3, 3))
matrix_difference = matrix_diff_a - matrix_diff_b
print("\nМатриця 1:\n", matrix_diff_a)
print("Матриця 2:\n", matrix_diff_b)
print("Різниця:\n", matrix_difference)


Матриця 1:
 [[9 4 2]
 [6 2 3]
 [4 1 7]]
Матриця 2:
 [[9 7 5]
 [7 5 8]
 [3 9 6]]
Різниця:
 [[ 0 -3 -3]
 [-1 -3 -5]
 [ 1 -8  1]]


In [11]:
#9. Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в діапазоні від -5 до 5 та знайдіть їх добуток.
matrix_mult_a = np.random.randint(-5, 6, (3, 3))
matrix_mult_b = np.random.randint(-5, 6, (3, 3))
matrix_multiplication = np.dot(matrix_mult_a, matrix_mult_b)
print("\nМатриця 1:\n", matrix_mult_a)
print("Матриця 2:\n", matrix_mult_b)
print("Добуток:\n", matrix_multiplication)


Матриця 1:
 [[ 0 -3  1]
 [-5 -4  1]
 [ 3 -1 -4]]
Матриця 2:
 [[-2  3 -2]
 [-2 -1  5]
 [-1 -3  3]]
Добуток:
 [[  5   0 -12]
 [ 17 -14  -7]
 [  0  22 -23]]


In [12]:
#10.Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від -1 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.
matrix_sum = np.random.uniform(-1, 1, (3, 3))
vector_sum = np.sum(matrix_sum, axis=1).reshape(-1, 1)
print("\nМатриця:\n", matrix_sum)
print("Вектор-стовпчик сум рядків:\n", vector_sum)





Матриця:
 [[-0.92107429  0.96260725 -0.58241669]
 [ 0.80079184 -0.77580021 -0.46033489]
 [-0.2316642   0.28498859 -0.03130084]]
Вектор-стовпчик сум рядків:
 [[-0.54088373]
 [-0.43534327]
 [ 0.02202355]]
